---
abstract: 'Supervise concurrent worker processes'
author:
  - 'Rhesa Rozendaal <rhesa@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200011, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Supervised-Convenience
requires:
  Moose: 1.08
  MooseX::Getopt: 0.29
  POE::Component::Supervisor: 0.07
resources:
  repository: http://github.com/rhesa/proc-supervised-convenience
version: 1.01
